baseURL: https://tanyamurphy.netlify.app/
languageCode: en-us
title: Tanya Murphy
theme: liva-hugo
summaryLength: '10'
paginate: 6
disqusShortname: 'tanya_murphy'
enableEmoji: true
permalinks: 
  blog: /:year/:month/:day-:slug/
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  author: Tanya Murphy
  cookies:
    enable: no
    expire_days: 2
  copyright: '| copyright &copy; 2020 Tanya Murphy | Designed with [blogdown](https://bookdown.org/yihui/blogdown/), [Hugo](https://gohugo.io/), and [Liva theme](https://themes.gohugo.io/liva-hugo/)'
  description: This is meta description
  email: tanya.j.murphy@gmail.com
  googleAnalitycsID: 
  home: Home
  #location: Montreal, Canada
  logo: images/logo_vsmall.png
  favicon: images/logo_vsmall.png
  #mobile: 
  newsletter:
    content: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
      eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
      At vero
    enable: no
    title: Join Our Newsletter
  plugins:
    css:
      - URL: plugins/bootstrap/bootstrap.min.css
      - URL: plugins/slick/slick.css
      - URL: plugins/themify-icons/themify-icons.css
      - URL: plugins/venobox/venobox.css
    js:
      - URL: plugins/jQuery/jquery.min.js
      - URL: plugins/bootstrap/bootstrap.min.js
      - URL: plugins/slick/slick.min.js
      - URL: plugins/venobox/venobox.min.js
      - URL: plugins/search/fuse.min.js
      - URL: plugins/search/mark.js
      - URL: plugins/search/search.js
  preloader:
    enable: yes
    preloader: ''
  search:
    enable: yes
  social:
    - icon: ti-twitter-alt
      link: 'https://twitter.com/tmurphEpi'
      title: twitter
    - icon: ti-github
      link: 'https://github.com/TanyaMurphy'
      title: github
    - icon: ti-linkedin
      link: 'https://www.linkedin.com/in/tanya-murphy-8298a457/'
      title: linkedin
    - icon: ti-book
      link: 'https://scholar.google.ca/citations?hl=en&user=ZTnPBaoAAAAJ&view_op=list_works&sortby=pubdate'
      title: publications (google scholar)
menu:
  footer:
    - URL: about
      name: About
      weight: 1
    - URL: blog
      name: Posts
      weight: 2
    - URL: contact
      name: Contact
      weight: 3
  main:
    - URL: about
      name: About
      weight: 1
    - URL: blog
      name: Posts
      weight: 2

